version: '3.8' 

services:
  client:
    build:
      context: ./client   
      dockerfile: Dockerfile   
    ports:
      - "8501:8501"   
    volumes:
      - sqlite_data:/app/   

volumes:
  sqlite_data:   
